# Following https://medium.com/@vinoji2005/install-prometheus-on-kubernetes-tutorial-and-example-6b3c800e7e1c
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  # Adding the namespace is good practice for Helm charts
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |-
    {{- .Files.Get "prometheus/prometheus-k8s.yml" | nindent 4 }}

  metrics.rules.yml: |-
    {{- .Files.Get "prometheus/metrics.rules.yml" | nindent 4 }}

  alert.rules.yml: |-
    {{- .Files.Get "prometheus/alert.rules.yml" | nindent 4 }}