repos:
  - repo: local
    hooks:
      - id: openapi-lint
        name: Lint OpenAPI spec
        entry: npx
        args: ["--yes", "@redocly/cli", "lint", "api/openapi.yaml"]
        language: system
        files: api/openapi\.yaml$
        pass_filenames: false

# Global configuration
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: "3.0.0"
