repos:
  - repo: local
    hooks:
      - id: openapi-lint
        name: Lint OpenAPI spec
        entry: npx
        args: ["--yes", "@redocly/cli", "lint", "api/openapi.yaml"]
        language: system
        files: api/openapi\.yaml$
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: [--strict]
        exclude: .*/tests/.*\.py$
        additional_dependencies: [
            "pydantic", 
            "types-requests",
            "fastapi"
        ]

# Global configuration
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: "3.0.0"
