services:
  # Client service - UI
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - niche-explorer-network
    restart: unless-stopped
   
  # Server services
  monitoring:
    build:
      context: ./server
      dockerfile: src/monitoring/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - niche-explorer-network
    restart: unless-stopped

  report-generator:
    build:
      context: ./server
      dockerfile: src/report-generator/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - niche-explorer-network
    restart: unless-stopped

  rss-fetcher:
    build:
      context: ./server
      dockerfile: src/rss-fetcher/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - niche-explorer-network
    restart: unless-stopped


  # GenAI services
  genai:
    build:
      context: ./genai
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    networks:
      - niche-explorer-network
    restart: unless-stopped

networks:
  niche-explorer-network:
    driver: bridge 