# This file contains the default values for the Niche Explorer Helm chart.

replicaCount: 1
base_imagedomain: "ghcr.io/aet-devops25/team-dev_ops/"
release: "latest" # Update to branch name when not operating on main branch

# Client service

ui:
  name: client
  image_name: client
  port: 80
  pullPolicy: Always
  
service:
  api:
    name: api-server
    image_name: api-server
    port: 8080
    pullPolicy: Always
    env:
      GENAI_BASE_URL: "http://genai:8000"
      FETCHER_BASE_URL: "http://article-fetcher:8200"
      TOPIC_BASE_URL: "http://topic-discovery:8100"

  genai:
    name: genai
    image_name: genai
    port: 8000
    pullPolicy: Always

  topic_discovery:
    name: topic-discovery
    image_name: topic-discovery
    port: 8100
    pullPolicy: Always

  article_fetcher:
    name: article-fetcher
    image_name: article-fetcher
    port: 8200
    pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  student_id: "ge74tif" # <TODO: Placeholder student ID>
  base_host: ".student.k8s.aet.cit.tum.de" # <TODO: Replace with actual FQDN>
  # tls: true
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"