# Template taken from: https://github.com/Mtze/kubernetes-templates/
apiVersion: v1
kind: Service
metadata:
  name: embeddeploy-service
  namespace: team-dev-ops
spec:
  selector:
    app: embeddeploy
  ports:
  - port: 8083 # TODO Placeholder port, replace with actual port
    targetPort: embeddeploy-api