# Template taken from: https://github.com/Mtze/kubernetes-templates/
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: team-dev-ops
spec:
  selector:
    app: ui
  ports:
  - port: 8080 # TODO Placeholder port, replace with actual port
    targetPort: ui