services:
  # Client (React + Vite)
  client:
    build:
      context: ../web-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - niche-explorer-network
    depends_on:
      - api-server
    restart: unless-stopped

  # Spring Boot API server
  api-server:
    build:
      context: ../services/spring-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - niche-explorer-network
    depends_on:
      - genai
      - topic-discovery
      - article-fetcher
      - db
    restart: unless-stopped
    environment:
      - GENAI_BASE_URL=http://genai:8000
      - TOPIC_BASE_URL=http://topic-discovery:8100

  # GenAI service (FastAPI + Gemini)
  genai:
    build:
      context: ../services/py-genai
      dockerfile: Dockerfile
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY?err}
    ports:
      - "8000:8000"
    networks:
      - niche-explorer-network
    restart: unless-stopped
    env_file:
      - ../.env

  # Postgres with pgvector extension
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: niche
      POSTGRES_PASSWORD: nichepw
      POSTGRES_DB: niche
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - niche-explorer-network
    restart: unless-stopped

  # Topic Discovery microservice
  topic-discovery:
    build:
      context: ../services/py-topics
      dockerfile: Dockerfile
    depends_on:
      - genai
    ports:
      - "8003:8100"
    networks:
      - niche-explorer-network
    restart: unless-stopped

  # Article Fetcher microservice
  article-fetcher:
    build:
      context: ../services/py-fetcher
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    networks:
      - niche-explorer-network
    restart: unless-stopped

networks:
  niche-explorer-network:
    driver: bridge

volumes:
  pgdata:
    driver: local 