services:
  # Client (React + Vite)
  client:
    build:
      context: ../
      dockerfile: web-client/Dockerfile
    ports:
      - "80:80"
    networks:
      - niche-explorer-network
    depends_on:
      - api-server

  # Spring Boot API server
  api-server:
    build:
      context: ../
      dockerfile: services/spring-api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - niche-explorer-network
    depends_on:
      - genai
      - topic-discovery
      - article-fetcher
      - db
    environment:
      - GENAI_BASE_URL=http://genai:8000
      - FETCHER_BASE_URL=http://article-fetcher:8200
      - TOPIC_BASE_URL=http://topic-discovery:8100
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # GenAI service (FastAPI + Gemini)
  genai:
    build:
      context: ../services/py-genai
      dockerfile: Dockerfile
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "60"]
    ports:
      - "8000:8000"
    networks:
      - niche-explorer-network
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHAIR_API_KEY=${CHAIR_API_KEY}

  # Postgres with pgvector extension
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - niche-explorer-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # Topic Discovery microservice
  topic-discovery:
    build:
      context: ../services/py-topics
      dockerfile: Dockerfile
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8100", "--timeout-keep-alive", "60"]
    depends_on:
      - genai
    ports:
      - "8100:8100"
    networks:
      - niche-explorer-network
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  # Article Fetcher microservice
  article-fetcher:
    build:
      context: ../services/py-fetcher
      dockerfile: Dockerfile
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8200", "--timeout-keep-alive", "60"]
    ports:
      - "8200:8200"
    networks:
      - niche-explorer-network

networks:
  niche-explorer-network:
    driver: bridge

volumes:
  pgdata:
    driver: local