genai:
  base-url: http://genai:8000

topic:
  base-url: http://topic-discovery:8100

fetcher:
  base-url: http://article-fetcher:8200

spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: genai-service
          uri: http://genai:8000
          predicates:
            - Path=/api/v1/classify, /api/v1/embeddings, /api/v1/query/**
        - id: article-fetcher-service
          uri: http://article-fetcher:8200
          predicates:
            - Path=/api/v1/articles, /api/v1/sources/**
        - id: topic-discovery-service
          uri: http://topic-discovery:8100
          predicates:
            - Path=/api/v1/topics/**
  main:
    web-application-type: reactive

flyway:
  baseline-on-migrate: false 