# Template taken from: https://github.com/Mtze/kubernetes-templates/
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.topic_discovery.name }}
spec:
  selector:
    app: {{ .Values.service.topic_discovery.name }}
  ports:
    - port: {{ .Values.service.topic_discovery.port }}
      targetPort: {{ .Values.service.topic_discovery.name }}
