genai:
  base-url: http://genai:8000

topic:
  base-url: http://topic-discovery:8100

fetcher:
  base-url: http://article-fetcher:8200

spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  baseline-on-migrate: false
