genai:
  base-url: http://genai:8000

topic:
  base-url: http://topic-discovery:8100

fetcher:
  base-url: http://article-fetcher:8200

spring:
  datasource:
    url: jdbc:postgresql://db:5432/niche
    username: niche
    password: nichepw
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  baseline-on-migrate: false
