{
 "title": "Finer Niche API Calls",
 "description": "A more detailled view at calls to the api's inside the microservices",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Classify and Embedding Calls (1d)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/d" } },
   "targets": [
    {
     "expr": "job:http_requests_total:classify_and_embeddings",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classify and Embedding Calls (1h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/h" } },
   "targets": [
    {
     "expr": "job:http_requests_total:classify_and_embeddings:1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classify and Embedding Calls (1m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "job:job:http_requests_total:classify_and_embeddings:1m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArXiv & Reddit Fetched Articles (1d)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "req/d" } },
   "targets": [
    { "expr": "job:arxiv_fetch_total:1d", "legendFormat": "__auto" },
    { "expr": "job:reddit_fetch_total:1d", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ArXiv & Reddit Fetched Articles (1h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "req/h" } },
   "targets": [
    { "expr": "job:arxiv_fetch_total:1h", "legendFormat": "__auto" },
    { "expr": "job:reddit_fetch_total:1h", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ArXiv & Reddit Fetched Articles (1m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "job:arxiv_fetch_total:1m", "legendFormat": "__auto" },
    { "expr": "job:reddit_fetch_total:1m", "legendFormat": "__auto" }
   ]
  }
 ]
}