{
 "title": "Niche Application Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(up,$job)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total requests to each Microservice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "targets": [
    { "expr": "job:http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Rate (last 5 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "job:http_requests_total:rate5m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "job:http_request_duration_seconds:avg1m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (5m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " job:http_requests_error:rate5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job:http_requests_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}