# /etc/prometheus/rules/service_rules.yml
groups:

- name: service-alerts
  rules:
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service '{{ $labels.job }}' is down"
      description: "The service '{{ $labels.job }}' at instance '{{ $labels.instance }}' has been down for more than 1 minute."

- name: genai_alerts
  rules:

  # /api/v1/classify
  - alert: HighRequestRateGenAI_Classify
    expr: sum(rate(http_requests_total{job="genai", handler="/api/v1/classify"}[1m])) > 0.0666 # 4 calls/minute
    for: 1m
    labels:
      severity: warning
      service: genai
      endpoint: classify
    annotations:
      summary: "High request rate detected on genai Classify endpoint"
      description: "The request rate to the genai /api/v1/classify endpoint ({{ $value }} requests per minute) is approaching the Gemini free tier limit of 5 RPM."

  # /api/v1/classify
  - alert: HighTotalRequestsGenAI_Classify
    expr: sum(round(increase(http_requests_total{job="genai", handler="/api/v1/classify"}[10m]))) > 50
    for: 1m
    labels:
      severity: warning
      service: genai
      endpoint: classify
    annotations:
      summary: "High total request count detected on genai Classify endpoint"
      description: "The total number of requests to the genai /api/v1/classify endpoint ({{ $value }} requests) has exceeded 50 in the last 10 minutes, approaching the Gemini free tier daily limit of 100 RPD."

  # /api/v1/classify
  - alert: HighDailyRequestsGenAI_Classify
    expr: sum(round(increase(http_requests_total{job="genai", handler="/api/v1/classify"}[1d]))) > 90
    for: 1m
    labels:
      severity: critical
      service: genai
      endpoint: classify
    annotations:
      summary: "High daily request count detected on genai Classify endpoint"
      description: "The total number of requests to the genai /api/v1/classify endpoint today ({{ $value }} requests) has exceeded 90, nearing the Gemini 2.5 Pro free tier limit of 100 RPD."

  # /api/v1/embeddings
  - alert: HighRequestRateGenAI_Embedding
    expr: sum(rate(http_requests_total{job="genai", handler="/api/v1/embeddings"}[1m])) > 0.0666 # 4 calls/minute
    for: 1m
    labels:
      severity: warning
      service: genai
      endpoint: embedding
    annotations:
      summary: "High request rate detected on genai Embedding endpoint"
      description: "The request rate to the genai /api/v1/embeddings endpoint ({{ $value }} requests per minute) is approaching the Gemini free tier limit of 5 RPM."

  # /api/v1/embeddings
  - alert: HighTotalRequestsGenAI_Embedding
    expr: sum(round(increase(http_requests_total{job="genai", handler="/api/v1/embeddings"}[10m]))) > 50
    for: 1m
    labels:
      severity: warning
      service: genai
      endpoint: embedding
    annotations:
      summary: "High total request count detected on genai Embedding endpoint"
      description: "The total number of requests to the genai /api/v1/embeddings endpoint ({{ $value }} requests) has exceeded 50 in the last 10 minutes, approaching the Gemini free tier daily limit of 100 RPD."
  
  # /api/v1/embeddings
  - alert: HighDailyRequestsGenAI_Embedding
    expr: sum(round(increase(http_requests_total{job="genai", handler="/api/v1/embeddings"}[1d]))) > 90
    for: 1m
    labels:
      severity: critical
      service: genai
      endpoint: embedding
    annotations:
      summary: "High daily request count detected on genai Embedding endpoint"
      description: "The total number of requests to the genai /api/v1/embeddings endpoint today ({{ $value }} requests) has exceeded 90, nearing the Gemini 2.5 Pro free tier limit of 100 RPD."


- name: article_fetcher_alerts
  rules:
  
  # /api/v1/articles arXiv api
  - alert: HighRequestRateArticleFetcher_ArxivInternal
    expr: sum(rate(arxiv_fetch_total{job="article-fetcher"}[1m])) > 0.266 # 16 calls/minute
    for: 1m
    labels:
      severity: warning
      service: article-fetcher
      endpoint: arxiv_internal
    annotations:
      summary: "High internal call rate to ArXiv fetcher detected"
      description: "The article-fetcher is making calls to the ArXiv service at a high rate ({{ printf \"%.2f\" $value }} requests per second). This might approach external API limits."

  - alert: HighTotalRequestsArticleFetcher_ArxivInternal
    expr: sum(round(increase(arxiv_fetch_total{job="article-fetcher"}[10m]))) > 150
    for: 1m
    labels:
      severity: warning
      service: article-fetcher
      endpoint: arxiv_internal
    annotations:
      summary: "High total internal calls to ArXiv fetcher (10m)"
      description: "The article-fetcher has made {{ $value }} calls to the ArXiv service in the last 10 minutes."

  - alert: HighDailyRequestsArticleFetcher_ArxivInternal
    expr: sum(round(increase(arxiv_fetch_total{job="article-fetcher"}[1d]))) > 2000
    for: 1m
    labels:
      severity: critical
      service: article-fetcher
      endpoint: arxiv_internal
    annotations:
      summary: "High daily internal calls to ArXiv fetcher (1d)"
      description: "The article-fetcher has made {{ $value }} calls to the ArXiv service today, nearing daily external API limits."

  # /api/v1/articles reddit fetcher - since Reddit uses rss feeds, just assume similar rate to arXiv
  - alert: HighRequestRateArticleFetcher_RedditInternal
    expr: sum(rate(reddit_fetch_total{job="article-fetcher"}[1m])) > 0.266 # 16 calls/minute
    for: 1m
    labels:
      severity: warning
      service: article-fetcher
      endpoint: reddit_internal
    annotations:
      summary: "High internal call rate to Reddit fetcher detected"
      description: "The article-fetcher is making calls to the Reddit service at a high rate ({{ printf \"%.2f\" $value }} requests per second). This might approach external API limits."

  - alert: HighTotalRequestsArticleFetcher_RedditInternal
    expr: sum(round(increase(reddit_fetch_total{job="article-fetcher"}[10m]))) > 150
    for: 1m
    labels:
      severity: warning
      service: article-fetcher
      endpoint: reddit_internal
    annotations:
      summary: "High total internal calls to Reddit fetcher (10m)"
      description: "The article-fetcher has made {{ $value }} calls to the Reddit service in the last 10 minutes."

  - alert: HighDailyRequestsArticleFetcher_RedditInternal
    expr: sum(round(increase(reddit_fetch_total{job="article-fetcher"}[1d]))) > 2000
    for: 1m
    labels:
      severity: critical
      service: article-fetcher
      endpoint: reddit_internal
    annotations:
      summary: "High daily internal calls to Reddit fetcher (1d)"
      description: "The article-fetcher has made {{ $value }} calls to the Reddit service today, nearing daily external API limits."