# ./prometheus/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'genai'
    metrics_path: /metrics
    static_configs:
      - targets: ['genai:8000']

  - job_name: 'topic-discovery'
    metrics_path: /metrics
    static_configs:
      - targets: ['topic-discovery:8100']

  - job_name: 'article-fetcher'
    metrics_path: /metrics
    static_configs:
      - targets: ['article-fetcher:8200']
rule_files:
  - "traefik_rules.yml"