groups:
  - name: traefik.rules
    rules:

      - record: traefik_requests_total
        expr: traefik_entrypoint_requests_total

      - record: traefik_requests_total_by_entrypoint
        expr: traefik_entrypoint_requests_total{entrypoint="web"}

      - record: traefik_requests_total_by_entrypoint_metrics
        expr: traefik_entrypoint_requests_total{entrypoint="metrics"}

      - record: traefik_requests_sum_by_entryPoint
        expr: sum by(entrypoint) (traefik_entrypoint_requests_total)

      - record: traefik_requests_histogram_quantile_for_95th_percentile
        expr: histogram_quantile(0.95, sum(rate(traefik_entrypoint_request_duration_seconds_bucket[5m])) by (le, entrypoint)) 

      - record: traefik_requests_sum_by_service
        expr: sum by (service) (rate(traefik_service_requests_total[5m]))
      
      - record: traefik_requests_sum_by_entrypoint_rate
        expr: sum by (entrypoint) (rate(traefik_entrypoint_requests_total[5m]))
        
      - record: traefik_requests_histogram_quantile_for_95th_percentile_by_service
        expr: histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket[5m])) by (le, service))

      - record: traefik_requests_histogram_quantile_for_95th_percentile_by_entrypoints
        expr: histogram_quantile(0.95, sum(rate(traefik_entrypoint_request_duration_seconds_bucket[5m])) by (le, entrypoint))

      - record: traefik_requests_sum_by_service_4xx
        expr: sum by (service) (rate(traefik_service_requests_total{code=~"4.."}[5m]))