apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  sessionAffinity: None
  type: {{ .Values.grafana.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}