server:
  port: 8082

spring:
  application:
    name: report-generator

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 