# Template taken from: https://github.com/Mtze/kubernetes-templates/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embeddeploy
  namespace: team-dev-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embeddeploy
  template:
    metadata:
      labels:
        app: embeddeploy
    spec:
      containers:
      - name: embeddeploy
        image: "nginxdemos/hello" # <TODO: Placeholder image, replace with actual RSS feed API image>
        ports:
          - containerPort: 8083 # <TODO: Placeholder port, replace with actual port>
            name: embeddeploy-api