# Template taken from: https://github.com/Mtze/kubernetes-templates/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: team-dev-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: "nginxdemos/hello" # <TODO: Placeholder image, replace with actual RSS feed API image>
        ports:
          - containerPort: 8080 # <TODO: Placeholder port, replace with actual port>
            name: ui