api:
  dashboard: true
log:
  level: INFO
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /letsencrypt/acme.json
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" # Staging server to bypass rate limits for testing
      tlsChallenge: {}