# Setup and configured getting help from Gemini.
# templates/db-deployment.yaml
{{- if .Values.pgvector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgvector.host }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.pgvector.image.repository }}:{{ .Values.pgvector.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pgvector.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          {{- if .Values.pgvector.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.pgvector.existingSecret }}
          {{- else }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.pgvector.postgresql.username | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.pgvector.postgresql.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}-secret
                  key: POSTGRES_PASSWORD
          {{- end }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}-pvc
{{- end }}