{{- if .Values.ingress.tls.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-issuer
spec:
  acme:
    email: {{ .Values.ingress.tls.issuer.acme.email | quote }}
    
    server: {{ .Values.ingress.tls.issuer.acme.server | quote }}
    
    privateKeySecretRef:
      name: {{ .Values.ingress.tls.issuer.acme.privateKeySecretName }}
      
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.ingress.className }}

{{- end }}