# Setup and configured getting help from Gemini.
# templates/pvc.yaml
{{- if .Values.pgvector.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}-pvc
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.pgvector.persistence.storageClass }}
  storageClassName: {{ .Values.pgvector.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pgvector.persistence.size }}
{{- end }}