# This file contains the default values for the Niche Explorer Helm chart.

replicaCount: 1
base_imagedomain: "ghcr.io/aet-devops25/team-dev_ops/"

server:
  rss_feed:
    name: rss-feed
    image_name: trend-dashboard
    port: 8083
    pullPolicy: Always
  
  report_generator:
    name: report-gen
    image_name: content-ingestion
    port: 8081
    pullPolicy: Always

  embeddeploy:
    name: embeddeploy
    image_name: growth-calculation
    port: 8082
    pullPolicy: Always

  source_detector:
    name: source-det
    image_name: monitoring
    port: 8084
    pullPolicy: Always

client:
  ui:
    name: ui
    image_name: client
    port: 8080
    pullPolicy: Always

ingress:
  enabled: true
  className: "nginx"
  student_id: "ge74tif"
  base_host: ".student.k8s.aet.cit.tum.de" # <TODO: Replace with actual FQDN>
  # tls: true
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"