# This file contains the default values for the Niche Explorer Helm chart.

replicaCount: 1
base_imagedomain: "ghcr.io/aet-devops25/team-dev_ops/"

server:
  rss_feed:
    name: rss-feed
    image_name: trend-dashboard # <TODO: Placeholder image, replace with actual RSS feed API image>
    port: 8083 # <TODO: Placeholder port, replace with actual port>
    pullPolicy: Always
  
  report_generator:
    name: report-gen
    image_name: content-ingestion # <TODO: Placeholder image, replace with actual RSS feed API image>
    port: 8081 # <TODO: Placeholder port, replace with actual port>
    pullPolicy: Always

  embeddeploy:
    name: embeddeploy
    image_name: growth-calculation # <TODO: Placeholder image, replace with actual RSS feed API image>
    port: 8082 # <TODO: Placeholder port, replace with actual port>
    pullPolicy: Always

  source_detector:
    name: source-det
    image_name: monitoring # <TODO: Placeholder image, replace with actual RSS feed API image>
    port: 8084 # <TODO: Placeholder port, replace with actual port>
    pullPolicy: Always

client:
  ui:
    name: ui
    image_name: client # <TODO: Placeholder image, replace with actual RSS feed API image>
    port: 8080 # <TODO: Placeholder port, replace with actual port>
    pullPolicy: Always