name: Minimal SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    environment:
      name: AWS
      url: 'https://your-ec2-ip-placeholder.nip.io' 
    steps:      
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          debug: true
          script: |
            echo "Attempting to connect and list home directory..."
            ls -la ~/ # List home directory of the remote user
            echo "SSH connection test completed."