name: Deploy Helm Chart

on:
  workflow_run:
    workflows: [Build Docker Images]
    types:
      - completed
  workflow_dispatch:

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy the monitring stack and the application.
        run: |
          bash ./infra/helm/deploy.sh
