name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'api/openapi.yaml'
      - '.github/workflows/docs.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build API docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install doc generators
        run: |
          npm install --location=global redoc-cli swagger-ui-dist

      - name: Generate ReDoc HTML
        run: |
          redoc-cli bundle api/openapi.yaml -o docs/api.html

      - name: Build Swagger UI static site
        run: |
          SWAGGER_DIST=$(npm root -g)/swagger-ui-dist
          mkdir -p docs/swagger
          cp -R "$SWAGGER_DIST"/* docs/swagger/
          # Copy spec next to the viewer
          cp api/openapi.yaml docs/swagger/openapi.yaml
          # Replace default initializer with one that loads our spec
          cat > docs/swagger/swagger-initializer.js <<'EOF'
          window.onload = function() {
            window.ui = SwaggerUIBundle({
              url: "openapi.yaml",
              dom_id: '#swagger-ui',
              presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIBundle.SwaggerUIStandalonePreset
              ],
              layout: "BaseLayout"
            });
          };
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    name: Deploy to GitHub Pages
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deploy
        uses: actions/deploy-pages@v4 