name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'api/openapi.yaml'
      - '.github/workflows/docs.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build API docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install doc generators
        run: |
          npm install --location=global redoc-cli swagger-ui-dist

      - name: Generate ReDoc HTML
        run: |
          redoc-cli bundle api/openapi.yaml -o docs/api.html

      - name: Build Swagger UI static site
        run: |
          SWAGGER_DIST=$(npm root -g)/swagger-ui-dist
          mkdir -p docs/swagger
          cp -R "$SWAGGER_DIST"/* docs/swagger/
          # Copy spec next to the viewer
          cp api/openapi.yaml docs/swagger/openapi.yaml
          # Rewrite default index to load local spec
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|openapi.yaml|' docs/swagger/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    name: Deploy to GitHub Pages
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deploy
        uses: actions/deploy-pages@v4 