name: Manual Undeploy

on:
  workflow_dispatch:

jobs:
  undeploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Undeploying the monitoring stack and the application.
        run: |
          bash ./infra/helm/undeploy.sh